[package]
name = "topojson-client"
version = "0.1.0"
edition = "2024"

[lib]
name = "topojson"
crate-type = ["cdylib"]

[dependencies]
json = "0.12.4"
serde = { version = "1.0.228", features = ["derive"] }
pyo3 = { version = "0.27.0", features = ["macros", "serde"] }
